= Humans in the loop idea to code workflow and tools

My GenAI-assisted idea to code workflow and supporting tools (Claude custom commands and link:docs/scripts/scripts.adoc[shell scripts] that run Claude).

== About humans in the loop development

If you want quality software then must be developed by human developers - GenAI plays the role of an assistant, not a developer.

**The human developer is responsible for the delivered software**

A GenAI coding agent must write code iteratively using TDD.

The developer must carefully review any GenAI-generated code and provide prompt feedback.
For example, the scripts described below run `claude` interactively, which enables prompt intervention by the developer.

== Installing Claude Code

See https://microservices.io/post/architecture/2025/07/09/vibe-coding-good-almost-other-part-2.html[Vibe coding: the good, the almost, and the @#$%** - Part 2], which describes how to get started with the Claude Code - a command-line based coding agent.

== The idea to code workflow

My GenAI-assisted idea to code workflow consists of the following steps:

. Exploring an idea - an interactive, GenAI-driven Q&A session to flesh out an idea
. Creating a specification - GenAI creates a specification from the Q&A session
. Optionally creating user stories and scenarios - it's sometimes useful to create user stories/scenarios
. Creating an implementation plan - a sequence tasks that are prompts for a coding agent
. Executing the implementation plan - running the coding agent to execute the plan

To use this workflow simply run:

[source,bash]
----
./idea-to-code.sh ~/ideas/my-new-idea
----

where `~/ideas/my-new-idea` is a directory that will contain the idea, spec, and implementation plan.

=== An example

Let's look at the example scenario - the development of https://github.com/humansintheloop-dev/humansintheloop-dev-examples-loctree[`loctree`], a terminal user interface (TUI) application that provides an interactive, hierarchical view of lines of code (LOC) counts for a given directory structure.

See link:./docs/idea-to-code-workflow.adoc[idea to code workflow]

== Acknowledgement

The original inspiration and some prompts came from this https://harper.blog/2025/02/16/my-llm-codegen-workflow-atm/[excellent post].

